### ISSUE TITLE
有关 pytorch框架实现的densefcn

### ISSUE THREAD

**Issue by Linql7** [ZhuangPeiyu/Dense-FCN-for-tampering-localization#3]
关注到您最新的研究reloc框架中使用了Densefcn作为定位模块，但关注到您发布的dense-fcn是使用tensorflow实现的，请问您是否有pytorch版本实现的dense-fcn代码？

**Comment by ZhuangPeiyu** [comment]
有啊，ReLoc项目下就有对应的Pytorch版本的代码。
